### ISSUE TITLE
for documentation section

### ISSUE THREAD

**Issue by gjanee** [ESIPFed/Software-Assessment-Guidelines#11]
Sorry, hypothes.is isn't letting me add an annotation.  If it's not too late, for "source code is documented" section, a couple more paragraphs:

Documentation of variables and data structures is generally more important and valuable than documentation of the code using those variables.  This is particularly true for variables that are shared across a module, a library, or the entire program.  Code is more likely to be self-explanatory if it is grounded in a good understanding of the data being operated upon.

Document standard practices and program invariants that would otherwise be unstated.  As software projects grow larger, standard coding practices can emerge that are not codified in any one place.  For example, it might be a standard practice that wherever and whenever a certain class of actions is taken a record is written to a log file.  Similarly, program rules and invariants can emerge that would ideally be enforced by the code, but for various reasons might not be.  For example, the correctness of the code might rely on the fact that updates to one data structure are always performed after updates to another.  Be sensitive to when such practices and invariants arise and document them, so that future developers are aware of and can continue the patterns.

**Comment by roomthily** [comment]
Apologies for the late response.

> Documentation of variables and data structures is generally more important and valuable than documentation of the code using those variables. This is particularly true for variables that are shared across a module, a library, or the entire program. Code is more likely to be self-explanatory if it is grounded in a good understanding of the data being operated upon.

We do mention describing parameters at different levels in the documentation. Is there a need for a stronger statement?

> Document standard practices and program invariants that would otherwise be unstated. As software projects grow larger, standard coding practices can emerge that are not codified in any one place. For example, it might be a standard practice that wherever and whenever a certain class of actions is taken a record is written to a log file. Similarly, program rules and invariants can emerge that would ideally be enforced by the code, but for various reasons might not be. For example, the correctness of the code might rely on the fact that updates to one data structure are always performed after updates to another. Be sensitive to when such practices and invariants arise and document them, so that future developers are aware of and can continue the patterns.

For this concept, I have been thinking about it in terms of the main audience of the document, the PI/manager. Mostly this means asking two questions for any guideline/description: are we describing it without jargon (understanding that a CS background is not likely) but accurately? and how broadly applicable is the concept and can we incorporate it with reasonable actionable steps? For me, this is bit too far into a technical detail. But, going up a bit back to assertions more generally, that is something missing the Testing section as a valuable tool for folks to learn about. My preference is to add a graf under Testing to mention assertions more broadly and point to references that cover the different uses, like invariants, in more detail.

**Comment by gjanee** [comment]
> Documentation of variables and data structures is generally more important and valuable than documentation of the code using those variables. This is particularly true for variables that are shared across a module, a library, or the entire program. Code is more likely to be self-explanatory if it is grounded in a good understanding of the data being operated upon.
> 
> We do mention describing parameters at different levels in the documentation. Is there a need for a stronger statement?

It's possible it's already covered, but I didn't see it.  Here's an example of what I'm trying to get at (actual code excerpt).  At the head of a program:

   'Declare Public Variables
   Public PTemp, batt_volt
   Public Tip(16)
   Public SoilMoisture(12)
   Public SoilTemperature(16)
   Public SoilTempOut(16)
   Public PlatRh
   Public PlatTemperature
   Public Snow_T107_C(8)
   Public Plat_depth
   Public RemoteBoom_depth
   Public WindMast_depth
   Public Plat_SnowPillow(2)
   Public Plat_Snow_Pillow_total
   Public SnowPillow2
   Public Tip_eng(16)
   Public CoTwo, BunkerTemp
   Public Barometer
   Public Forest_Sno_Pillow

Later in the code it becomes apparent that Tip_eng is volume of snowmelt water in liters, in part because there are helpful comments wherever Tip_eng appears like "Calculate Volume from first 8 tipping buckets".  I maintain, though, that it is preferable to document the meaning of the variable where it is defined.  As a nice side effect of doing that, the need to document what is going on in the code is lessened.

**Comment by gjanee** [comment]
> It's possible it's already covered, but I didn't see it.  Here's an example of what I'm trying to get at (actual code excerpt).  At the head of a program:
> 
>   'Declare Public Variables
>   Public PTemp, batt_volt
>   Public Tip(16)
>   Public SoilMoisture(12)
>   Public SoilTemperature(16)
>   Public SoilTempOut(16)
>   Public PlatRh
>   Public PlatTemperature
>   Public Snow_T107_C(8)
>   Public Plat_depth
>   Public RemoteBoom_depth
>   Public WindMast_depth
>   Public Plat_SnowPillow(2)
>   Public Plat_Snow_Pillow_total
>   Public SnowPillow2
>   Public Tip_eng(16)
>   Public CoTwo, BunkerTemp
>   Public Barometer
>   Public Forest_Sno_Pillow
> 
> Later in the code it becomes apparent that Tip_eng is volume of snowmelt water in liters, in part because there are helpful comments wherever Tip_eng appears like "Calculate Volume from first 8 tipping buckets".  I maintain, though, that it is preferable to document the meaning of the variable where it is defined.  As a nice side effect of doing that, the need to document what is going on in the code is lessened.

The point being in this example that there is documentation on what these parameters are, but it is scattered and buried in the code.

**Comment by gjanee** [comment]
> Document standard practices and program invariants that would otherwise be unstated. As software projects grow larger, standard coding practices can emerge that are not codified in any one place. For example, it might be a standard practice that wherever and whenever a certain class of actions is taken a record is written to a log file. Similarly, program rules and invariants can emerge that would ideally be enforced by the code, but for various reasons might not be. For example, the correctness of the code might rely on the fact that updates to one data structure are always performed after updates to another. Be sensitive to when such practices and invariants arise and document them, so that future developers are aware of and can continue the patterns.
> 
> For this concept, I have been thinking about it in terms of the main audience of the document, the PI/manager. Mostly this means asking two questions for any guideline/description: are we describing it without jargon (understanding that a CS background is not likely) but accurately? and how broadly applicable is the concept and can we incorporate it with reasonable actionable steps? For me, this is bit too far into a technical detail. But, going up a bit back to assertions more generally, that is something missing the Testing section as a valuable tool for folks to learn about. My preference is to add a graf under Testing to mention assertions more broadly and point to references that cover the different uses, like invariants, in more detail.

I struggled with how to phrase this, so yes, perhaps it's too technical for this audience.
