### ISSUE TITLE
for current browser versions section

### ISSUE THREAD

**Issue by gjanee** [ESIPFed/Software-Assessment-Guidelines#12]
I would mention at least one framework explicitly, as in:

Web application pages that contain JavaScript or other dynamic elements should be built on a framework such as <hyperlink>jQuery</hyperlink>.  But while front-end frameworks and libraries have greatly improved cross-browser support, it's still important...

**Comment by roomthily** [comment]
How's this:

> Front-end frameworks and libraries have greatly improved cross-browser support, but it’s still important to ensure that the web application functions as intended across any and all browsers supported by the project. Any modern Javascript framework, whether the more generic JQuery or interface frameworks like React, Backbone, or Ember, will provide cross-browser support.

**Comment by gjanee** [comment]
Sounds good
