### ISSUE TITLE
link to 'references.html'  --> 'resources.html' ?

### ISSUE THREAD

**Issue by emielvanloon** [ESIPFed/Software-Assessment-Guidelines#25]
It think this link in the document:
https://esipfed.github.io/Software-Assessment-Guidelines/references.html
should be:
https://esipfed.github.io/Software-Assessment-Guidelines/resources.html

**Comment by emielvanloon** [comment]
And to add to myself: I am referring to index.html

In which
<a href="{{ site.baseurl }}/references.html"> could be changed into <a href="{{ site.baseurl }}/resources.html">

**Comment by roomthily** [comment]
Yes, good catch!
